## **PyTorch Basic**

---
- 참고도서
  - 파이토치 첫걸음(두세교, 제이펍)
  - 펭귄브로의 3분 딥러닝 파이토치맛(김건우,염상준/한빛미디어)
---

In [1]:
import numpy as np
import torch

### GPU 설정 

In [2]:
# torch.cuda.is_available()를 통해 현재 시스템의 상태를 인식, 지정하면 GPU또는 CPU를 상황에 맞게 적용할 수 있다.
# device='cuda' 또는 device='cuda:0'와 같은 방법으로 직접 지정할 수 있다. (0: GPU의 Index)

USE_CUDA = torch.cuda.is_available()
DEVICE = torch.device('cuda' if USE_CUDA else 'cpu')
print(DEVICE)

cpu


### 텐서 사용

In [4]:
# 중첩 list 지정 

t = torch.tensor([[1,2],[3,4]])
print(t)

# device를 지정하면 GPU로 Tensor를 만들 수 있다
#t = torch.tensor([[1, 2], [3, 4.]], device='cuda')
# print(t)

# dtype을 사용해 데이터형을 지정해 Tensor를 만들 수 있다
t = torch.tensor([[1, 2], [3, 4.]], dtype=torch.float64)
print(t)

tensor([[1, 2],
        [3, 4]])
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [5]:
# 0부터 9까지의 수치로 초기화된 1차원 Tensor

t = torch.arange(0,10)
t

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
t.type

<function Tensor.type>

In [ ]:
#모든 값이 0인 100 x 10 의 Tensor를 작성해서 to메서드로 GPU에 전송
if DEVICE == 'cuda':
  t = torch.zeros(100, 10).to("cuda:0")
else:
  t = torch.zeros(100, 10)

print(t)

In [7]:
# 정규 난수로 100 x 10의 Tensor를 작성

t = torch.randn(100, 10)
print(t)

tensor([[-2.1699e-01, -5.2965e-02, -3.4378e-01, -5.9348e-01,  7.3880e-01,
          2.4961e-01, -1.8819e+00,  9.0851e-01,  4.5204e-01,  2.9426e-01],
        [-1.3024e+00,  1.5562e+00, -8.1578e-01, -1.0337e+00,  1.0532e+00,
         -4.7755e-01,  6.7262e-01, -9.8217e-01, -1.1557e+00,  1.3149e+00],
        [-4.2555e-01, -4.1287e-01, -3.8849e-01,  1.8163e-01,  9.0451e-01,
         -1.0898e-01, -6.3003e-01, -4.2686e-01, -2.1443e-01,  2.3242e-01],
        [-6.2981e-01, -5.1910e-01,  2.3895e+00,  1.0481e+00, -5.5689e-01,
          1.8969e+00, -1.5006e+00, -1.3201e+00, -2.4045e-01,  1.9969e+00],
        [-2.7088e-01, -6.3692e-01,  4.9533e-02, -1.3281e+00,  1.3418e+00,
          5.4482e-01,  1.4168e-01,  6.4393e-02,  1.1681e+00,  3.5606e-01],
        [ 7.8165e-01,  1.1579e+00, -3.4079e-01, -1.2838e+00,  7.1688e-01,
         -8.7400e-01, -7.9106e-01,  6.5199e-01,  1.3498e+00, -2.6406e-01],
        [-6.2294e-01, -7.9365e-01,  3.8823e-02, -4.3465e-01,  2.2192e+00,
         -2.3200e-01, -9.4726e-0

In [8]:
# Tensor의 shape은 size 메서드로 취득 가능
t.size()

torch.Size([100, 10])

In [9]:
# numpy 메서드를 사용해 ndarray로 변환

t = torch.tensor([[1,2],[3,4]])
x = t.numpy()
x

array([[1, 2],
       [3, 4]])

In [11]:
# GPU上상의 Tensor는 cpu메서드로,
# CPU의 Tensor로 이동(변환)할 필요가 있다

t = torch.tensor([[1, 2], [3, 4.]], device="cuda:0")
x = t.to("cpu").numpy()
x

array([[1, 2],
       [3, 4]])

In [12]:
t = torch.tensor([[1,2,3], [4,5,6.]])

# 스칼라 첨자 지정
print(t[0, 2])

# 슬라이스로 지정
print(t[:, :2])

# 리스트로 지정
print(t[:, [1,2]])

# 마스크 배열을 시용해서 3보다 큰 부분만 선택
print(t[t > 3])

tensor(3.)
tensor([[1., 2.],
        [4., 5.]])
tensor([[2., 3.],
        [5., 6.]])
tensor([4., 5., 6.])


In [14]:
# [0, 1]의 요소를 100으로 설정
t[0, 1] = 100
print(t)

# 슬라이스를 사용한 일괄 대입
t[:, 1] = 200
print(t)      

# 마스크 배열을 사용해서 특정 조건의 요소만 치환
t[t > 10] = 20
print(t)

tensor([[  1., 100.,   3.],
        [  4.,   5.,   6.]])
tensor([[  1., 200.,   3.],
        [  4., 200.,   6.]])
tensor([[ 1., 20.,  3.],
        [ 4., 20.,  6.]])


In [15]:
# 길이 3인 벡터
v = torch.tensor([1, 2, 3.])
w = torch.tensor([0, 10, 20.])
print('v=', v)
print('w=', w)
print('----------------------------------------------')

# 2 × 3의 행렬
m = torch.tensor([[0, 1, 2], [100, 200, 300.]])
print('m=', m)
print('----------------------------------------------')

# 벡터와 스칼라의 덧셈
v2 = v + 10
print('v2=', v2)

# 자승도 같은 방식
v2 = v ** 2
print('v2=', v2)

# 동일 길이의 벡터 간 뺄쎔
z = v - w
print('z=', z)

# 여러 가지 조합
u = 2 * v - w / 10 + 6.0
print('u=', u)
print('----------------------------------------------')

# 행렬과 스칼라
m2 = m * 2.0
print('m2=', m2)
# 행렬과 벡터
#(2, 3)인 행렬과 (3,)인 벡터이므로 브로드 캐스트가 작동
m3 = m + v
print('m3=', m3)
# 행렬 간 처리
m4 = m + m
print('m4=', m4)
print('----------------------------------------------')


v= tensor([1., 2., 3.])
w= tensor([ 0., 10., 20.])
----------------------------------------------
m= tensor([[  0.,   1.,   2.],
        [100., 200., 300.]])
----------------------------------------------
v2= tensor([11., 12., 13.])
v2= tensor([1., 4., 9.])
z= tensor([  1.,  -8., -17.])
u= tensor([ 8.,  9., 10.])
----------------------------------------------
m2= tensor([[  0.,   2.,   4.],
        [200., 400., 600.]])
m3= tensor([[  1.,   3.,   5.],
        [101., 202., 303.]])
m4= tensor([[  0.,   2.,   4.],
        [200., 400., 600.]])
----------------------------------------------


In [16]:
# 100 × 10의 테스트 데이터 생성
X = torch.randn(100, 10)
print(X)
print("X=", X)
print('----------------------------------------------')

# 수학 함수를 포함하는 수식
y = X * 2 + torch.abs(X)
print("y=", y)
print('----------------------------------------------')

# 평균치 구하기
m = torch.mean(X)
print('m=', m)
print('----------------------------------------------')

# 함수가 아닌 메서드로도 사용할 수 있다
m = X.mean()
print('m=', m)
print('----------------------------------------------')

# 집계 결과는 0차원의 Tensor로 item 메서드를 사용해서
# 값을 추출할 수 있다
m_value = m.item()
print('m_value=', m_value)
print('----------------------------------------------')

# 집계는 차원을 지정할 수도 있다. 다음은 행 방향으로 집계해서,
# 열 단위로 평균값을 계산한다
m2 = X.mean(0)
print('m2=', m2)
print('----------------------------------------------')

tensor([[ 6.4571e-01,  6.0937e-01, -8.0749e-01,  3.3516e-02, -4.6925e-01,
         -1.3685e+00,  9.5302e-01,  3.8236e-01, -1.5792e+00,  9.1862e-01],
        [ 1.1260e+00,  9.4433e-01,  3.3654e-01, -1.4254e+00, -7.8049e-01,
         -1.3336e+00, -4.6019e-01,  5.4222e-01, -1.6966e-01, -1.1974e+00],
        [-4.5550e-01,  9.3576e-01,  5.1516e-02, -1.6513e+00,  1.1611e+00,
         -4.1254e-01,  5.5275e-01,  2.1325e-01,  7.1438e-01, -1.0524e-01],
        [ 4.7494e-01, -1.1980e+00,  1.0590e+00,  7.1677e-01,  4.8533e-01,
         -1.5191e+00,  1.1851e+00, -8.8968e-01, -1.0636e+00, -8.3811e-01],
        [-1.6237e+00, -2.1884e-01, -2.7159e-01,  1.2649e+00, -9.7017e-02,
          1.5068e+00, -4.1145e-01,  1.1481e+00, -9.7889e-01, -2.6083e+00],
        [-5.1446e-01, -1.4452e+00, -3.8833e-01,  2.4477e-01, -2.4900e-01,
          2.0762e+00,  2.0494e+00,  2.7378e-01,  2.1324e+00, -1.5770e+00],
        [-1.2015e-01, -5.2069e-01,  6.0019e-01, -6.8940e-01, -3.2713e-01,
         -6.5057e-01,  1.5005e+0

In [17]:
x1 = torch.tensor([[1, 2], [3, 4.]]) # 2×2
x2 = torch.tensor([[10, 20, 30], [40, 50, 60.]]) # 2×3

# 2×2를 4×1로 보여준다
print(x1)
print(x1.view(4, 1))
print('----------------------------------------------')

# -1는 나머지 차원을 나타내며 한 번만 사용할 수 있다
# 아래 예에선 -1을 사용하면 자동으로 4가 된다
print(x1.view(1, -1))
print('----------------------------------------------')

# 2×3을 전치해서 3×2로 만든다
print(x2.t())
print('----------------------------------------------')

# dim=1로 결합하면 2×5의 Tensor를 만든다
torch.cat([x1, x2], dim=1)

tensor([[1., 2.],
        [3., 4.]])
tensor([[1.],
        [2.],
        [3.],
        [4.]])
----------------------------------------------
tensor([[1., 2., 3., 4.]])
----------------------------------------------
tensor([[10., 40.],
        [20., 50.],
        [30., 60.]])
----------------------------------------------


tensor([[ 1.,  2., 10., 20., 30.],
        [ 3.,  4., 40., 50., 60.]])

In [18]:
# HWC을 CHW로 변환
# 64×32×3의 데이터가 100개
hwc_img_data = torch.rand(100, 64, 32, 3)
print(hwc_img_data)
print('----------------------------------------------')
chw_img_data = hwc_img_data.transpose(1, 2).transpose(1, 3)
print(chw_img_data)

tensor([[[[2.0557e-01, 1.0135e-01, 9.1603e-01],
          [5.9690e-02, 9.6901e-01, 9.5652e-01],
          [3.5018e-01, 3.9301e-01, 3.6614e-01],
          ...,
          [8.2160e-02, 1.2465e-02, 3.1500e-01],
          [3.5412e-01, 4.3982e-02, 8.0166e-01],
          [4.2487e-01, 8.5945e-01, 5.0867e-01]],

         [[1.4069e-01, 4.6965e-01, 3.3208e-01],
          [2.7193e-01, 8.5790e-02, 4.6590e-01],
          [5.4025e-01, 5.7298e-01, 2.8044e-01],
          ...,
          [6.8755e-01, 3.7067e-01, 8.4082e-01],
          [6.3919e-01, 8.2873e-01, 6.1652e-01],
          [7.6064e-01, 6.3499e-03, 9.1085e-01]],

         [[4.5976e-01, 1.7878e-01, 2.6775e-01],
          [8.9024e-01, 2.6819e-01, 3.5249e-01],
          [4.1065e-01, 1.3250e-01, 7.9328e-01],
          ...,
          [3.8198e-01, 1.6478e-01, 4.9412e-01],
          [1.3730e-01, 1.7072e-01, 4.9312e-01],
          [5.2468e-01, 9.5959e-01, 7.4798e-01]],

         ...,

         [[5.6583e-01, 4.3932e-01, 9.7938e-01],
          [1.6834e-01,

In [19]:
m = torch.randn(100, 10)
v = torch.randn(10)
print('m = ', m)
print('v = ', v)

# 내적
d = torch.dot(v, v)
print('d = v·v = ', d)
print('----------------------------------------------')

# 100 × 10의 행렬과 길이 10인 벡터의 곱
# 결과는 길이 100인 벡터
v2 = torch.mv(m, v)
print('v2 = ', v2)
print('----------------------------------------------')

# 행렬곱
m2 = torch.mm(m.t(), m)
print('m2 = ', m2)
print('----------------------------------------------')

# 특이값 분해
u, s, v = torch.svd(m)
print('u = ', u)
print('s = ', s)
print('v = ', v)

m =  tensor([[ 4.7871e-01,  1.6816e+00,  1.9529e-01, -9.6101e-01, -2.7211e-01,
          3.6741e-01, -1.9526e-01,  2.2642e-01, -2.5086e-01,  2.7420e-01],
        [-3.4309e-01, -1.9574e-01, -3.2006e-02, -6.7432e-01, -1.5296e-02,
         -1.3871e-01, -2.0211e+00, -1.0757e+00,  5.4349e-01,  3.2246e-01],
        [ 2.3120e+00,  1.3764e-01, -1.7871e+00,  1.8538e+00, -2.4206e-02,
         -5.2007e-01, -1.3210e+00,  5.2018e-01, -4.8354e-01, -1.4225e+00],
        [ 1.2992e+00,  4.6282e-01, -8.2076e-01, -9.3444e-01, -1.3766e-01,
         -5.6577e-01, -1.9428e+00, -1.4996e+00, -3.7166e-01, -1.4627e-01],
        [-2.5021e-01,  2.0092e+00, -5.6024e-01, -1.8410e-01,  6.8231e-03,
          1.4690e+00,  1.1543e+00, -2.9695e-02, -2.4081e-01, -7.6341e-01],
        [ 9.4836e-02,  5.3452e-01,  9.0909e-01,  9.3984e-01, -3.8575e-01,
          2.1002e+00,  2.5950e-01, -6.3127e-02, -5.6514e-01, -6.8063e-02],
        [-1.1138e+00, -3.5974e-01,  1.0916e+00,  7.2189e-01,  8.5206e-01,
         -1.1338e+00, -1.48

In [20]:
x = torch.randn(100, 3)
print('x = ', x)
print('----------------------------------------------')

# 미분의 변수로 사용하는 경우는 requires_grad를 True로 설정
a = torch.tensor([1, 2, 3.], requires_grad=True)
print('a = ', a)
print('----------------------------------------------')

# 계산을 통해 자동으로 계산 그래프가 구축된다
y = torch.mv(x, a)
o = y.sum()
print('o = ', o)
print('----------------------------------------------')

# 미분을 실행
o.backward()

# 분석 답과 비교
a.grad != x.sum(0)

x =  tensor([[ 0.4201,  0.0643,  0.7847],
        [-0.4304,  0.3665, -0.9750],
        [-0.2976,  0.1171, -0.3583],
        [ 1.4585, -0.3279,  0.1748],
        [ 0.0273, -0.6582,  0.9366],
        [-0.2765,  1.2173, -1.2746],
        [-2.5316,  0.1577, -1.4724],
        [-0.7600,  0.3529, -1.2250],
        [ 1.5883,  0.2819,  1.2137],
        [-0.3507, -0.3570, -0.3790],
        [ 0.9817,  0.8557,  0.6577],
        [ 0.5018, -1.8189, -0.2135],
        [ 1.0500, -1.1698,  1.0142],
        [-0.0141, -0.5375,  0.6073],
        [-1.5627, -0.4391, -0.7352],
        [-0.1192,  0.6364,  1.1047],
        [ 0.0161,  1.3702, -1.8421],
        [-2.4452, -0.0724,  0.4547],
        [ 2.1864,  0.2593,  0.3401],
        [-1.3913, -1.9900, -0.2103],
        [-0.1521,  0.3329,  2.1741],
        [ 1.1160, -0.2433, -0.2641],
        [ 2.4111, -0.5662, -0.8357],
        [-0.1202,  0.5676,  0.8411],
        [ 0.7691, -0.0255,  0.6294],
        [ 0.8169,  1.1640,  0.2010],
        [-0.2130, -0.3307,  0.338

tensor([ True, False,  True])

## Tensor and Autograd

In [24]:
x = torch.tensor([[1,2,3],[4,5,6], [7,8,9]])
print(x)

print('size', x.size())
print('shape', x.shape)
print('랭크(차원):',x.ndimension())

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
size torch.Size([3, 3])
shape torch.Size([3, 3])
랭크(차원): 2


In [25]:
# 랭크 늘리기 
# 특정 위치에 1인 차원을 추가
x = torch.unsqueeze(x, 0)
print(x)
print("Size:", x.size())
print("Shape:", x.shape)
print("랭크(차원):", x.ndimension())

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
Size: torch.Size([1, 3, 3])
Shape: torch.Size([1, 3, 3])
랭크(차원): 3


In [27]:
x = torch.unsqueeze(x , 1)
print('랭크(차원):', x.ndimension())

랭크(차원): 5


In [28]:
print(x)

tensor([[[[[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]]]]])


In [29]:
# 차원이 1인 경우에는 해당 차원을 제거
x = torch.squeeze(x, 0)
print('랭크(차원):', x.ndimension())

랭크(차원): 4


In [30]:
# 랭크 줄이기
x = torch.squeeze(x)
print(x)
print("Size:", x.size())
print("Shape:", x.shape) #[3, 3] 2개의 차원에 각 3개의 원소를 가진 텐서
print("랭크(차원):", x.ndimension())

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Size: torch.Size([3, 3])
Shape: torch.Size([3, 3])
랭크(차원): 2


#### 파이토치 텐서의 뷰(View)는 넘파이에서의 리쉐이프(Reshape)와 같은 역할을 한다.Reshape라는 이름에서 알 수 있듯이, 텐서의 크기(Shape)를 변경해주는 역할한다.

In [32]:
# 랭크의 형태 바꾸기
# 원소의 수를 유지하면서 텐서의 크기 변경
x = x.view(9)
print(x)
print("Size:", x.size())
print("Shape:", x.shape)
print("랭크(차원):", x.ndimension())

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
Size: torch.Size([9])
Shape: torch.Size([9])
랭크(차원): 1


In [31]:
try:
    x = x.view(2,4)
except Exception as e:
    print(e) #에러 출력

shape '[2, 4]' is invalid for input of size 9


## Tensor 연산과 행렬곱

In [33]:
w = torch.randn(5,3, dtype = torch.float)
x = torch.tensor([[1.0,2.0], [3.0,4.0], [5.0,6.0]])
print("w size:", w.size())
print("x size:", x.size())
print("w:", w)
print("x:", x)

w size: torch.Size([5, 3])
x size: torch.Size([3, 2])
w: tensor([[ 0.0594, -0.1186, -0.7240],
        [ 0.1768,  0.6160,  0.9830],
        [-0.3742, -0.4598,  1.7600],
        [ 0.7535, -1.2524, -1.4005],
        [-0.5548, -0.5027, -1.0180]])
x: tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])


In [34]:
b = torch.randn(5,2, dtype=torch.float)
print("b:", b.size())
print("b:", b)

b: torch.Size([5, 2])
b: tensor([[ 0.0090,  0.5255],
        [ 0.9526,  0.1862],
        [-0.8845,  3.1597],
        [ 1.2247,  2.6529],
        [ 0.3865, -1.4390]])


In [35]:
# torch.mm 행렬곱 

wx = torch.mm(w,x) # w의 행은 5, x의 열은 2, 즉 shape는 [5, 2]입니다.
print("wx size:", wx.size())
print("wx:", wx)

wx size: torch.Size([5, 2])
wx: tensor([[ -3.9166,  -4.6998],
        [  6.9397,   8.7155],
        [  7.0463,   7.9723],
        [-10.0063, -11.9058],
        [ -7.1528,  -9.2282]])


In [36]:
result = wx + b	
print("result size:", result.size()) 
print("result:", result) 

result size: torch.Size([5, 2])
result: tensor([[ -3.9076,  -4.1743],
        [  7.8924,   8.9016],
        [  6.1618,  11.1320],
        [ -8.7816,  -9.2528],
        [ -6.7663, -10.6673]])


## 자동미분(Autograd)
- 사용법
  1. 계산하고자 하는 수식 생성
  2. 수식을 위한 requires_grad 값을 True로 설정. 파이토치의 Autograd 기능으로 자동 계산할 때 수식에 대한 미분값을 '수식.grad'에 저장
  3. backward() 함수를 사용하여 수식에 연쇄법칙을 적용하고 수식을 차례대로 미분


In [37]:
w = torch.tensor(1.0, requires_grad=True) # True 미분 가능하게 함 

In [38]:
a = w*3
l = a**2
l.backward() # 미분 
print(w.grad)
print('l을 w로 미분한 값은 {}'.format(w.grad))

tensor(18.)
l을 w로 미분한 값은 18.0
